### ISSUE TITLE
AttributeError in pyramid_tween 

### ISSUE THREAD

**Issue by slav0nic** [AppEnlight/appenlight-client-python#55]
appenlight don't work correct with `bound method` views
```pytb
Traceback (most recent call last):
File "/mnt/data/work/zojax/quickpyramid/lib/python3.7/site-packages/websauna/system/auth/tweens.py", line 60, in __call__
    response = self.handler(request)
File "quick/dashboard/tweens.py", line 54, in __call__
    response = self.handler(request)
File "pyramid/router.py", line 148, in handle_request
    registry, request, context, context_iface, view_name
File "pyramid/view.py", line 657, in _call_view
    response = view_callable(context, request)
File "pyramid/viewderivers.py", line 384, in authdebug_view
    return view(context, request)
File "pyramid/viewderivers.py", line 514, in csrf_view
    return view(context, request)
File "appenlight_client/ext/pyramid_tween.py", line 99, in view_callable_wrapper
    original_view._appenlight_name = view_name
AttributeError: 'method' object has no attribute '_appenlight_name'

```
`original_view` is 
`<bound method Sitemap.render of <quick.core.sitemap.Sitemap object at 0x7f48755c51d0>>`

Pyramid support bounded method, but you can't set attr on it, internally i find some workaround for solve this: https://github.com/Pylons/pyramid/blob/587fe72fae0efda3a860d37a1ea2449a41dab622/src/pyramid/viewderivers.py#L94

Sample View for reproduce error:
```py
sm = Sitemap()
...
config.add_route("sitemap", "/sitemap.xml")
config.add_view(sm.render, route_name="sitemap", renderer="core/sitemap.xml")
```

**Comment by ergo** [comment]
Can you please make a small reproductible test case that I can use?

**Comment by slav0nic** [comment]
app/\_\_init\_\_.py
```py
from pyramid.config import Configurator
from pyramid.response import Response

def view1(request):
    return Response('View 1')

class View2:
    def render(self, context, request):
        return Response('View 2')

def main(global_config, **settings):
    view2 = View2()
    with Configurator() as config:
        config.include('appenlight_client.ext.pyramid_tween')
        config.add_route('v1', '/v1')
        config.add_view(view1, route_name='v1')
        config.add_route('v2', '/v2')
        config.add_view(view2.render, route_name='v2')
        config.scan()
    return config.make_wsgi_app()
```

app.ini (here i use `filter-with` with `app:main`, that looks similar to `pipeline:main` + `filter: ...` and not required changes for default pyramid scaffold)
```ini
[app:main]
use = egg:app#main
filter-with = appenlight_client

[filter:appenlight_client]
use = egg:appenlight_client
appenlight.api_key = 123

[server:main]
use = egg:waitress#main
listen = 0.0.0.0:6543
```

setup.py
```py
from setuptools import setup, find_packages
requires = [
    'pyramid',
    'waitress',
    'appenlight-client'
]
setup(name='app',
    packages=find_packages(),
    install_requires=requires,
     entry_points="""
     [paste.app_factory] 
     main = app:main
      """,
)
```
so, `/v2` stop work if appenlight enabled

**Comment by slav0nic** [comment]
Quick fix like this diff work, but i don't know how it correct related to pyramid internals, also don't know about old pyramid version support (`from pyramid.util import is_bound_method`)
Just a  wrap function (you can set) that return original_view:
```diff
diff --git a/appenlight_client/ext/pyramid_tween.py b/appenlight_client/ext/pyramid_tween.py
index c0dc9a1..e7548da 100644
--- a/appenlight_client/ext/pyramid_tween.py
+++ b/appenlight_client/ext/pyramid_tween.py
@@ -2,6 +2,7 @@
 from appenlight_client.timing import get_local_storage
 from appenlight_client.utils import fullyQualifiedName
 from pyramid.tweens import EXCVIEW
+from pyramid.compat import is_bound_method
 import pkg_resources
 import pyramid.config
 import logging
@@ -95,6 +96,10 @@ def view_callable_wrapper(context, request):
             original_view = getattr(appenlight_callable, '__original_view__')
             if original_view:
                 view_name = fullyQualifiedName(appenlight_callable)
+                if is_bound_method(original_view):
+                    _original_view = original_view
+                    def original_view(context, request):
+                        return _original_view(context, request)
                 if not hasattr(original_view, '_appenlight_name'):
                     original_view._appenlight_name = view_name
         except Exception:
```

**Comment by ergo** [comment]
Fixed in trunk
